apiVersion: v1
kind: Pod
metadata:
  name: test-pod-100
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep infinity"]
    env:
    - name: MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
    - name: NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
  restartPolicy: Never
