apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-1
  name: pod-1
spec:
  containers:
  - image: debian
    name: pod-1
    resources: {}
    command: ["/bin/sh"]
    args: 
    - "-c" 
    - "while true; do echo HI $(FNAME) $(LNAME); echo --------; sleep 10; done"
    env:
    - name: FNAME
      value: "Mike"
    - name: LNAME
      value: "Rapuano" 
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
