apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-1
  name: pod-1
spec:
  containers:
  - image: debian
    name: helper
    command: ["/bin/sh"]
    args: ["-c", "echo hi mike > /data/temp/index.html"]
    volumeMounts:
    - name: web-storage
      mountPath: /data/temp
  - image: nginx
    name: pod-1
    volumeMounts:
    - name: web-storage
      mountPath: /usr/share/nginx/html
    resources: {}
  volumes:
  - name: web-storage
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
