apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-pod
    my-label: test
  name: test-pod
spec:
  containers:
  - image: bash
    name: test-pod
    command: ["bash"]
    args: ["-c", "hostname >> /tmp/hostname && sleep 600"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
