apiVersion: v1
kind: Pod
metadata:
  name: test-pod-99
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "env"]
    env:
    - name: GAME
      valueFrom:
        configMapKeyRef:
          name: special-config-dir
          key: game.properties
    - name: UI
      valueFrom:
         configMapKeyRef:
           name: special-config-dir
           key: ui.properties
  restartPolicy: Never
