apiVersion: v1
kind: Pod
metadata:
  name: test-pod-99
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "env"]
    envFrom:
    - configMapRef:
        name: special-config-500
  restartPolicy: Never
