apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  namespace: qos-example
  labels:
    run: pod-03
  name: pod-03
spec:
  containers:
  - image: busybox
    name: pod-03
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 10; done"]
    resources: 
      requests:
        cpu: 150m
        memory: 200Mi
      limits:
        cpu: 150m
        memory: 200Mi
  dnsPolicy: ClusterFirst
  restartPolicy: OnFailure
status: {}
