apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  namespace: qos-example
  labels:
    run: pod-01
  name: pod-01
spec:
  containers:
  - image: busybox
    name: pod-01
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 10; done"]
    resources:  {}
  dnsPolicy: ClusterFirst
  restartPolicy: OnFailure
status: {}
