apiVersion: v1
kind: LimitRange
metadata:
  name: qos-limit-range
  namespace: qos-example
spec:
  limits:
  - default:
      cpu: 500m
      memory: 500Mi
    defaultRequest:
      cpu: 250m
      memory: 250Mi
    max:
      cpu: 750m
      memory: 550Mi
    min:
      cpu: 150m
      memory: 200Mi
    type: Container 
