apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-1
  name: pod-1
spec:
  containers:
  - image: nginx
    name: pod-1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
