apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-pod
    my-label: test
  name: test-pod
spec:
  containers:
  - image: bash
    name: test-pod
    command: ["bash"]
    args: ["-c", "while true; do sleep 10; done"]
    resources: {}
    volumeMounts:
    - name: literal-name
      mountPath: /etc/literal
    - name: game-file
      mountPath: /etc/game
    - name: multi-file
      mountPath: /etc/ui
    - name: dir-files
      mountPath: /etc/dir_files
    - name: env-file
      mountPath: /etc/env-files
  volumes:
  - name: literal-name 
    configMap:
      name: literal-name 
  - name: game-file
    configMap:
      name: game-file
  - name: multi-file
    configMap:
      name: multi-file
      items:
      - key: ui.properties
        path: my/shit.txt
  - name: dir-files
    configMap:
      name: dir-files
  - name: env-file
    configMap:
      name: env-file
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
